Allow Creeper: true
Allow Cave Spider: true
Allow Dragon: true
Allow Enderman: true
Allow Ghast: true
Allow Giant: true
Allow Silverfish: true
Allow Skeleton: true
Allow Slime: true
Allow Squid: true
Allow Zombie: true